In [51]:
import pandas as pd

In [52]:
customers=pd.read_csv("C:/Users/Supradha/ E-Commerce User Funnel & Drop-off Analysis/dataset/olist_customers_dataset.csv")

In [53]:
customers

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP
...,...,...,...,...,...
99436,17ddf5dd5d51696bb3d7c6291687be6f,1a29b476fee25c95fbafc67c5ac95cf8,3937,sao paulo,SP
99437,e7b71a9017aa05c9a7fd292d714858e8,d52a67c98be1cf6a5c84435bd38d095d,6764,taboao da serra,SP
99438,5e28dfe12db7fb50a4b2f691faecea5e,e9f50caf99f032f0bf3c55141f019d99,60115,fortaleza,CE
99439,56b18e2166679b8a959d72dd06da27f9,73c2643a0a458b49f58cea58833b192e,92120,canoas,RS
99440,274fa6071e5e17fe303b9748641082c8,84732c5050c01db9b23e19ba39899398,6703,cotia,SP

In [54]:
customers.shape

(99441, 5)

In [55]:
customers.dtypes

customer_id                 object
customer_unique_id          object
customer_zip_code_prefix     int64
customer_city               object
customer_state              object
dtype: object

In [56]:
customers.isnull().sum()

customer_id                 0
customer_unique_id          0
customer_zip_code_prefix    0
customer_city               0
customer_state              0
dtype: int64

In [57]:
# duplicate rows
customers.duplicated().sum()

0

In [58]:
customers['customer_id'].duplicated().sum()

0

In [59]:
# Remove full duplicate rows 
customers.drop_duplicates(inplace=True)

In [60]:
# Standardise string columns 
customers['customer_city']  = (customers['customer_city'].str.strip().str.lower().str.title())

In [61]:
customers['customer_state'] = (customers['customer_state'].str.strip().str.upper())

In [62]:
# Validate customer_state
# Brazil has 27 states (26 + DF)
valid_states = [
    'AC','AL','AP','AM','BA','CE','DF','ES','GO',
    'MA','MT','MS','MG','PA','PB','PR','PE','PI',
    'RJ','RN','RS','RO','RR','SC','SP','SE','TO']

In [63]:
invalid_states = customers[~customers['customer_state'].isin(valid_states)]

In [64]:
print(f"\n  Rows with invalid state code : {len(invalid_states)}")
if len(invalid_states) > 0:
    print(invalid_states[['customer_state']].value_counts())

  Rows with invalid state code : 0

In [65]:
# Validate zip code 
# Brazilian zip codes are 5-digit numbers
customers['zip_valid'] = (customers['customer_zip_code_prefix'].astype(str).str.match(r'^\d{5}$'))

In [66]:
print(f"\n  Invalid zip codes : " f"{(~customers['zip_valid']).sum()}")

  Invalid zip codes : 23995

In [67]:
customers.shape

(99441, 6)

In [68]:
customers

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state,zip_valid
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,Franca,SP,True
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,Sao Bernardo Do Campo,SP,False
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,Sao Paulo,SP,False
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,Mogi Das Cruzes,SP,False
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,Campinas,SP,True
...,...,...,...,...,...,...
99436,17ddf5dd5d51696bb3d7c6291687be6f,1a29b476fee25c95fbafc67c5ac95cf8,3937,Sao Paulo,SP,False
99437,e7b71a9017aa05c9a7fd292d714858e8,d52a67c98be1cf6a5c84435bd38d095d,6764,Taboao Da Serra,SP,False
99438,5e28dfe12db7fb50a4b2f691faecea5e,e9f50caf99f032f0bf3c55141f019d99,60115,Fortaleza,CE,True
99439,56b18e2166679b8a959d72dd06da27f9,73c2643a0a458b49f58cea58833b192e,92120,Canoas,RS,True
99440,274fa6071e5e17fe303b9748641082c8,84732c5050c01db9b23e19ba39899398,6703,Cotia,SP,False

In [69]:
# top 10 states by customer count
print(customers['customer_state'].value_counts().head(10))

SP    41746
RJ    12852
MG    11635
RS     5466
PR     5045
SC     3637
BA     3380
DF     2140
ES     2033
GO     2020
Name: customer_state, dtype: int64

In [70]:
customers.to_csv("cleaned_customers.csv",index=False)